name: node 
 
on:
  workflow_dispatch:
jobs:
  send_message: 
    runs-on: ubuntu-latest
    name: node-wechat
    steps:
      
      - name: checkout
        uses: actions/checkout@master  
            
      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: '14'
          
      - name: Install Dependency       
        run: |
          npm install      
                   
      - name: Chmod       
        run: |
          chmod a+x natapp
          
      - name: Natapp       
        run: |
          ./natapp -h
      
