name: node 
 
on:
  schedule:   
    - cron: '0 0 * * *'   
  workflow_dispatch:
jobs:
  send_message: 
    runs-on: ubuntu-latest
    name: node-wechat
    steps:
      - name: Ngork       
        run: |
          ./natapp -authtoken=0083ee88dbe7d7fa          
          


      
